[project]
name = "azure-assistant"
version = "0.1.0"
description = "Minor CLI to communicate with Azure Openai"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "openai>=1.59.5",
]

[dependency-groups]
lint = [
    "ruff>=0.8.6",
]
